using QRCoder;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;
using System.Globalization;

namespace HpskSite.Services;

public static class SwishQrCodeGenerator
{
    /// <summary>
    /// Generates a Swish URL that can be used for direct payment links or QR codes.
    /// </summary>
    /// <param name="phoneNumber">10 digits, no +46. Ex: 0702123456</param>
    /// <param name="amount">Two decimals with dot. Ex: 100.00</param>
    /// <param name="message">Max 50 chars</param>
    /// <returns>Swish payment URL</returns>
    public static string GetSwishUrl(string phoneNumber, string amount, string message)
    {
        // --- Validate & normalize ---
        phoneNumber = NormalizePhone(phoneNumber);
        if (phoneNumber.Length != 10 || !phoneNumber.All(char.IsDigit))
        {
            throw new ArgumentException("Phone must be 10 digits like 0701234567.");
        }

        if (!IsAmountOk(amount))
        {
            throw new ArgumentException("Amount must be like 100.00 (dot as decimal, two decimals).");
        }

        message = message?.Trim() ?? string.Empty;
        if (message.Length > 50)
        {
            message = message[..50]; // Swish raw QR limit
        }

        var payload = $"C{phoneNumber};{amount};{message};0";
        return payload;
    }

    /// <summary>
    /// Generates a user-friendly Swish app link that opens directly in the Swish app on mobile devices.
    /// </summary>
    /// <param name="phoneNumber">10 digits, no +46. Ex: 0702123456</param>
    /// <param name="amount">Two decimals with dot. Ex: 100.00</param>
    /// <param name="message">Max 50 chars</param>
    /// <returns>Swish app URL (swish://)</returns>
    public static string GetSwishAppUrl(string phoneNumber, string amount, string message)
    {
        // Use the same validation as GetSwishUrl
        var payload = GetSwishUrl(phoneNumber, amount, message);
        
        // Create swish:// URL for direct app opening
        return $"swish://payment?data={Uri.EscapeDataString(payload)}";
    }

    /// <summary>
    /// Generates a Swish QR (PNG bytes) with a centered logo. Cross-platform (ImageSharp).
    /// </summary>
    /// <param name="phoneNumber">10 digits, no +46. Ex: 0702123456</param>
    /// <param name="amount">Two decimals with dot. Ex: 100.00</param>
    /// <param name="message">Max 50 chars</param>
    /// <param name="logoPath">Path to PNG logo (transparent is fine)</param>
    public static byte[] GeneratePng(string phoneNumber, string amount, string message,
        int pixelsPerModule = 20,
        int iconSizePercent = 25,
        int iconBorderWidth = 6)
    {
        // Use the new GetSwishUrl method for consistency
        var payload = GetSwishUrl(phoneNumber, amount, message);

        return GeneratePngFromUrl(payload, pixelsPerModule, iconSizePercent, iconBorderWidth);
    }

    /// <summary>
    /// Generates a Swish QR (PNG bytes) from a Swish URL with a centered logo.
    /// </summary>
    /// <param name="swishUrl">Swish URL generated by GetSwishUrl method</param>
    /// <param name="pixelsPerModule">QR code pixel size</param>
    /// <param name="iconSizePercent">Logo size percentage</param>
    /// <param name="iconBorderWidth">Logo border width</param>
    /// <returns>PNG bytes</returns>
    public static byte[] GeneratePngFromUrl(string swishUrl,
        int pixelsPerModule = 20,
        int iconSizePercent = 25,
        int iconBorderWidth = 6)
    {
        var gen = new QRCodeGenerator();
        using var data = gen.CreateQrCode(swishUrl, QRCodeGenerator.ECCLevel.Q);

        // Load the logo (any format supported by ImageSharp)
        var logoPath = Path.Combine(AppContext.BaseDirectory, "Swish Logo.png");
        if (!File.Exists(logoPath))
        {
            throw new FileNotFoundException("Swish logo not found.", logoPath);
        }

        using var icon = Image.Load<Rgba32>(logoPath);

        var qr = new QRCoder.QRCode(data);

        using var img = qr.GetGraphic(
            pixelsPerModule: pixelsPerModule,
            darkColor: Color.Black,
            lightColor: Color.White,
            icon: icon,
            iconSizePercent: iconSizePercent,
            iconBorderWidth: iconBorderWidth,
            drawQuietZones: true
        );

        using var ms = new MemoryStream();
        img.Save(ms, new PngEncoder()); 
        return ms.ToArray();
    }

    internal static string NormalizePhone(string input)
    {
        // Remove spaces and country code if someone passes +46
        var s = new string((input ?? string.Empty).Where(char.IsDigit).ToArray());
        // If it starts with 46 and then 7..., convert to 0 + rest
        if (s.StartsWith("46") && s.Length >= 11 && s[2] == '7')
        {
            s = "0" + s[2..];
        }

        return s;
    }

    internal static bool IsAmountOk(string amount)
    {
        // Must be dot as decimal and two decimals
        if (!decimal.TryParse(amount, NumberStyles.Number, CultureInfo.InvariantCulture, out var d))
        {
            return false;
        }

        // Preserve exact two decimals formatting
        var formatted = d.ToString("0.00", CultureInfo.InvariantCulture);
        return string.Equals(formatted, amount, StringComparison.Ordinal);
    }
}
