using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using HpskSite.CompetitionTypes.Common;
using HpskSite.Models;
using HpskSite.Models.Kretsgranskning;
using HpskSite.Services;
using HpskSite.Services.Kretsgranskning;
using HpskSite.Services.Mail;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Security;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;
using Umbraco.Extensions;

namespace HpskSite.Controllers
{
    /// <summary>
    /// Tävlingsansökan och kretskalendern (kretsgranskning fas 4).
    ///
    /// <list type="bullet">
    /// <item><b>Klubbsidan</b> (klubbens admin): skapa, ändra, skicka in, svara på komplettering,
    /// återkalla, och skapa tävlingen när kretsen sagt ja.</item>
    /// <item><b>Kretssidan</b> (kretsens tävlingsansvarige eller kretsadmin): begär komplettering,
    /// godkänn/avslå en kretstävling, tillstyrk/avstyrk en nationell eller landsdelsansökan,
    /// registrera Förbundets beslut, sista ansökningsdagar.</item>
    /// <item><b>Länkläget</b>: en krets utan tävlingsansvarig får ärendet som en länk utan inloggning
    /// (<c>/kretsen/arende?t=</c>), och beslutet stämplas med namn och roll.</item>
    /// <item><b>Kalendern</b>: öppen läsväg.</item>
    /// </list>
    ///
    /// <para><b>⚠️ Kretsen härleds ur KLUBBEN på servern</b>, aldrig ur klienten — en klubb kan inte
    /// skicka sin ansökan till en annan krets än sin egen.</para>
    /// </summary>
    public class CompetitionApplicationController : SurfaceController
    {
        private readonly CompetitionApplicationService _apps;
        private readonly KretsCalendarService _calendar;
        private readonly KretsUppdragService _uppdrag;
        private readonly KretsLinkTokenService _tokens;
        private readonly AdminAuthorizationService _auth;
        private readonly BoardRoleService _roles;
        private readonly IMemberManager _memberManager;
        private readonly IMemberService _memberService;
        private readonly EmailService _email;
        private readonly ReplyContactResolver _replyTo;
        private readonly ClubService _clubs;
        private readonly ILogger<CompetitionApplicationController> _logger;

        public CompetitionApplicationController(
            IUmbracoContextAccessor umbracoContextAccessor,
            IUmbracoDatabaseFactory databaseFactory,
            ServiceContext services,
            AppCaches appCaches,
            IProfilingLogger profilingLogger,
            IPublishedUrlProvider publishedUrlProvider,
            CompetitionApplicationService apps,
            KretsCalendarService calendar,
            KretsUppdragService uppdrag,
            KretsLinkTokenService tokens,
            AdminAuthorizationService auth,
            BoardRoleService roles,
            IMemberManager memberManager,
            IMemberService memberService,
            EmailService email,
            ReplyContactResolver replyTo,
            ClubService clubs,
            ILogger<CompetitionApplicationController> logger)
            : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        {
            _apps = apps;
            _calendar = calendar;
            _uppdrag = uppdrag;
            _tokens = tokens;
            _auth = auth;
            _roles = roles;
            _memberManager = memberManager;
            _memberService = memberService;
            _email = email;
            _replyTo = replyTo;
            _clubs = clubs;
            _logger = logger;
        }

        public const string CaseKind = "Ansokan";

        // Links generated by NotifyKretsAsync in THIS request (the controller is per request).
        // Returned only to a site admin - the support path, and how the link mode is verified
        // without SMTP. Everyone else only ever gets the link by mail.
        private readonly List<string> _caseLinks = new();

        private async Task<List<string>?> CaseLinksForSupportAsync() =>
            _caseLinks.Count > 0 && await _auth.IsCurrentUserAdminAsync() ? _caseLinks : null;

        // ════════════════════════════════════════════════════════════════════════════════
        //  Klubbsidan
        // ════════════════════════════════════════════════════════════════════════════════

        /// <summary>Klubbens ansökningar, kretsens sista dagar och om kretsen tar emot inloggat.</summary>
        [HttpGet]
        public async Task<IActionResult> GetClubApplications(int clubId)
        {
            if (!await _auth.IsClubAdminForClub(clubId)) return Json(new { success = false, message = "Åtkomst nekad" });

            var regionId = _calendar.RegionIdForClub(clubId);
            var region = _calendar.Region(regionId);
            var list = SafeList(() => _apps.ForClub(clubId));
            var holders = regionId > 0 ? _uppdrag.Holders(regionId, BoardRoleDefinitions.RoleTavlingsansvarig) : new();
            var year = DateTime.Today.Year;
            var linksThisYear = list.Count(a => !string.IsNullOrEmpty(a.LinkSentTo) && a.CreatedAt.Year == year);

            return Json(new
            {
                success = true,
                region = region == null ? null : new { id = region.Id, name = region.Name, url = region.Url },
                kretsReceivesLoggedIn = holders.Count > 0,
                linksThisYear,
                deadlines = regionId > 0 ? SafeList(() => _apps.Deadlines(regionId))
                    .Where(d => d.Year >= year).Select(d => new { d.Year, d.Level, lastDate = d.LastDate.ToString("yyyy-MM-dd") }) : null,
                levels = CompetitionApplicationRules.ApplicableLevels.Select(l => new { value = l, label = CompetitionLevel.Find(l)?.Label ?? l }),
                disciplines = HpskSite.Models.CompetitionTypes.All.Select(t => new { value = t.Id, label = t.Name }),
                applications = list.Select(a => Dto(a, forClub: true))
            });
        }

        /// <summary>Valen i ansökningsdialogen (nivåer och grenar). Öppet — inga uppgifter om någon.</summary>
        [HttpGet]
        public IActionResult GetApplicationOptions() => Json(new
        {
            success = true,
            levels = CompetitionApplicationRules.ApplicableLevels.Select(l => new { value = l, label = CompetitionLevel.Find(l)?.Label ?? l }),
            disciplines = HpskSite.Models.CompetitionTypes.All.Select(t => new { value = t.Id, label = t.Name })
        });

        /// <summary>En ansökan med händelselogg — för klubben eller kretsen.</summary>
        [HttpGet]
        public async Task<IActionResult> GetApplication(int id)
        {
            var a = _apps.Get(id);
            if (a == null) return Json(new { success = false, message = "Ansökan hittades inte." });
            var club = await CanClubAsync(a.ClubId, a.RegionId);
            var krets = (await KretsAuthorityAsync(a.RegionId)).Allowed;
            if (!club && !krets) return Json(new { success = false, message = "Åtkomst nekad" });
            return Json(new
            {
                success = true,
                application = Dto(a, forClub: club && !krets),
                events = _apps.Events(id).Select(e => new { at = e.At.ToString("yyyy-MM-dd HH:mm"), e.Kind, kindLabel = EventLabel(e.Kind), byName = e.ByName ?? "", e.Text }),
                canKrets = krets,
                canClub = club
            });
        }

        public class SaveApplicationRequest
        {
            public int Id { get; set; }
            public int ClubId { get; set; }
            /// <summary>Bara för kretsens egna ansökningar (ClubId = 0).</summary>
            public int RegionId { get; set; }
            public string Level { get; set; } = "";
            public string Discipline { get; set; } = "";
            public string Name { get; set; } = "";
            public string CompetitionDate { get; set; } = "";
            public string? EndDate { get; set; }
            public string? ReserveDate { get; set; }
            public int? RangeId { get; set; }
            public string? Place { get; set; }
            public string? ContactName { get; set; }
            public string? ContactEmail { get; set; }
            public string? ContactPhone { get; set; }
            public string? Classes { get; set; }
            public string? Note { get; set; }
            /// <summary>"1" = skicka in direkt. Sträng, eftersom "1" inte binder till bool.</summary>
            public string? Submit { get; set; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveApplication([FromBody] SaveApplicationRequest req)
        {
            if (req == null) return Json(new { success = false, message = "Tom begäran." });
            var me = await CurrentMemberAsync();
            if (me == null) return Json(new { success = false, message = "Logga in först." });

            // Kretsen härleds ur klubben, aldrig ur klienten.
            int regionId = req.ClubId > 0 ? _calendar.RegionIdForClub(req.ClubId) : req.RegionId;
            if (regionId <= 0) return Json(new { success = false, message = "Klubbens krets hittades inte." });
            if (!await CanClubAsync(req.ClubId, regionId)) return Json(new { success = false, message = "Åtkomst nekad" });

            var draft = new CompetitionApplication
            {
                RegionId = regionId,
                ClubId = Math.Max(0, req.ClubId),
                Level = (req.Level ?? "").Trim(),
                Discipline = (req.Discipline ?? "").Trim(),
                Name = (req.Name ?? "").Trim(),
                CompetitionDate = ParseDate(req.CompetitionDate) ?? default,
                EndDate = ParseDate(req.EndDate),
                ReserveDate = ParseDate(req.ReserveDate),
                RangeId = req.RangeId is > 0 ? req.RangeId : null,
                Place = Clip(req.Place, 200),
                ContactMemberId = me.Id,
                ContactName = Clip(req.ContactName, 200) ?? DisplayName(me),
                ContactEmail = Clip(req.ContactEmail, 200) ?? me.Email,
                ContactPhone = Clip(req.ContactPhone, 50),
                Classes = Clip(req.Classes, 400),
                Note = Clip(req.Note, 4000)
            };

            CompetitionApplication? saved;
            string? err;
            bool justSubmitted;
            if (req.Id > 0)
            {
                var existing = _apps.Get(req.Id);
                if (existing == null || existing.ClubId != draft.ClubId || existing.RegionId != regionId)
                    return Json(new { success = false, message = "Ansökan hittades inte." });
                (saved, err) = _apps.UpdateContent(req.Id, draft, me.Id, DisplayName(me));
                justSubmitted = false;
                if (saved != null && req.Submit == "1" && saved.Status == CompetitionApplicationStatus.Utkast)
                {
                    (saved, err) = _apps.Submit(saved.Id, me.Id, DisplayName(me));
                    justSubmitted = saved != null;
                }
            }
            else
            {
                (saved, err) = _apps.Create(draft, req.Submit == "1", me.Id, DisplayName(me));
                justSubmitted = saved?.Status == CompetitionApplicationStatus.Inskickad;
            }
            if (saved == null) return Json(new { success = false, message = err });

            var notified = 0;
            var lateNote = LateNote(saved);
            if (justSubmitted || (req.Id > 0 && saved.Status == CompetitionApplicationStatus.Inskickad))
                notified = await NotifyKretsAsync(saved, me, justSubmitted ? "Ny ansökan" : "Ändrad ansökan");

            _calendar.Invalidate();
            return Json(new
            {
                success = true,
                application = Dto(saved, forClub: true),
                notified,
                caseLinks = await CaseLinksForSupportAsync(),
                message = saved.Status == CompetitionApplicationStatus.Utkast
                    ? "Ansökan sparad som utkast. Den skickas till kretsen när du trycker Skicka in."
                    : (notified > 0
                        ? $"Ansökan är skickad till kretsen ({notified} {(notified == 1 ? "mottagare" : "mottagare")})."
                        : "Ansökan är sparad hos kretsen, men inget mejl kunde skickas. Kretsen ser den när någon där loggar in.")
                    + (lateNote != null ? " " + lateNote : "")
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitApplication(int id)
        {
            var (a, me, deny) = await ClubActionAsync(id);
            if (deny != null) return deny;
            var (saved, err) = _apps.Submit(id, me!.Id, DisplayName(me));
            if (saved == null) return Json(new { success = false, message = err });
            var n = await NotifyKretsAsync(saved, me, "Ny ansökan");
            _calendar.Invalidate();
            return Json(new { success = true, notified = n, caseLinks = await CaseLinksForSupportAsync(), message = n > 0 ? "Ansökan är skickad till kretsen." : "Ansökan är inskickad, men inget mejl kunde skickas." });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> WithdrawApplication(int id, string? reason)
        {
            var (a, me, deny) = await ClubActionAsync(id);
            if (deny != null) return deny;
            var (saved, err) = _apps.Withdraw(id, me!.Id, DisplayName(me), reason);
            if (saved == null) return Json(new { success = false, message = err });
            _calendar.Invalidate();
            return Json(new { success = true, message = "Ansökan är återkallad." });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReplyApplication(int id, string? text)
        {
            var (a, me, deny) = await ClubActionAsync(id);
            if (deny != null) return deny;
            var (saved, err) = _apps.Reply(id, text ?? "", me!.Id, DisplayName(me));
            if (saved == null) return Json(new { success = false, message = err });
            var n = await NotifyKretsAsync(saved, me, "Klubben har kompletterat");
            return Json(new { success = true, notified = n, caseLinks = await CaseLinksForSupportAsync(), message = "Svaret är skickat till kretsen." });
        }

        /// <summary>
        /// Det ansökan vet, för att förifylla tävlingsguiden. Inget sparas — tävlingen skapas först
        /// när arrangören slutför guiden, och kopplingen görs då på servern (CreateCompetition).
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> GetPrefill(int id)
        {
            var (a, me, deny) = await ClubActionAsync(id);
            if (deny != null) return deny;
            if (!CompetitionApplicationRules.CanCreateCompetition(a!))
                return Json(new { success = false, message = a!.CompetitionId is > 0 ? "Tävlingen är redan skapad." : "Kretsen har inte sagt ja ännu." });
            var region = _calendar.Region(a.RegionId);
            return Json(new
            {
                success = true,
                prefill = new
                {
                    applicationId = a.Id,
                    name = a.Name,
                    date = a.EffectiveDate.ToString("yyyy-MM-dd"),
                    endDate = a.EndDate?.ToString("yyyy-MM-dd"),
                    discipline = a.Discipline,
                    level = a.Level,
                    clubId = a.ClubId,
                    regionCode = region?.Code ?? "",
                    rangeId = a.RangeId,
                    venue = a.Place ?? "",
                    awaitingForbundet = a.Status == CompetitionApplicationStatus.HosForbundet
                }
            });
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  Kretssidan
        // ════════════════════════════════════════════════════════════════════════════════

        /// <summary>Kretsens inkorg och beslutade ansökningar för ett tävlingsår.</summary>
        [HttpGet]
        public async Task<IActionResult> GetRegionApplications(int regionId, int? year)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var y = year ?? DateTime.Today.Year + 1;
            var list = SafeList(() => _apps.ForRegion(regionId, new DateTime(y, 1, 1), new DateTime(y, 12, 31)));
            // ⚠️ En ansökan som väntar på kretsen visas ALLTID — årsväljaren får aldrig gömma arbete.
            // (Samma fel som granskningsinkorgen hade: en inskickad ansökan för ett annat år syntes inte.)
            var shown = list.Select(a => a.Id).ToHashSet();
            list.AddRange(SafeList(() => _apps.ForRegion(regionId, new DateTime(2000, 1, 1), new DateTime(2100, 12, 31)))
                .Where(a => a.Status == CompetitionApplicationStatus.Inskickad && !shown.Contains(a.Id)));
            var region = _calendar.Region(regionId);
            return Json(new
            {
                success = true,
                year = y,
                region = region == null ? null : new { id = region.Id, name = region.Name },
                forbundetDeadline = CompetitionApplicationRules.ForbundetDeadline(y).ToString("yyyy-MM-dd"),
                deadlines = SafeList(() => _apps.Deadlines(regionId)).Where(d => d.Year == y)
                    .Select(d => new { d.Level, lastDate = d.LastDate.ToString("yyyy-MM-dd") }),
                applications = list.Where(a => a.Status != CompetitionApplicationStatus.Utkast).Select(a => Dto(a, forClub: false)),
                actingAs = auth.Role
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RequestCompletion(int id, string? text)
        {
            var (a, who, deny) = await KretsActionAsync(id);
            if (deny != null) return deny;
            var (saved, err) = _apps.RequestCompletion(id, text ?? "", who!);
            if (saved == null) return Json(new { success = false, message = err });
            var n = await NotifyClubAsync(saved, who!, $"Kretsen ber om komplettering av ansökan \"{saved.Name}\"",
                new[] { $"{who!.Name} i {RegionName(saved.RegionId)} ber er komplettera ansökan om {saved.Name} ({saved.CompetitionDate:yyyy-MM-dd}):", saved.CompletionRequest ?? "",
                        "Svara i klubbens Administration → Tävlingar → Ansökningar. Ansökan ligger kvar hos kretsen under tiden." });
            return Json(new { success = true, notified = n, message = MailMessage(n, "Klubben är ombedd att komplettera") });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DecideApplication(int id, string? decision, string? text)
        {
            var (a, who, deny) = await KretsActionAsync(id);
            if (deny != null) return deny;
            var approve = decision == "approve";
            if (!approve && decision != "reject") return Json(new { success = false, message = "Okänt beslut." });
            var (saved, err) = _apps.Decide(id, approve, text, who!);
            if (saved == null) return Json(new { success = false, message = err });
            _calendar.Invalidate();
            var n = await NotifyClubAsync(saved, who!,
                approve ? $"Godkänd: {saved.Name}" : $"Avslagen: {saved.Name}",
                approve
                    ? new[] { $"{RegionName(saved.RegionId)} har godkänt ansökan om {saved.Name} den {saved.CompetitionDate:yyyy-MM-dd}.", saved.DecisionText ?? "",
                              "När ni vill lägga in tävlingen: gå till klubbens Administration → Tävlingar → Ansökningar och tryck Skapa tävlingen. Guiden är då förifylld med det ansökan innehåller." }
                    : new[] { $"{RegionName(saved.RegionId)} har avslagit ansökan om {saved.Name}.", "Motivering:", saved.DecisionText ?? "" });
            return Json(new { success = true, notified = n, message = MailMessage(n, approve ? "Ansökan är godkänd" : "Ansökan är avslagen") });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GiveOpinion(int id, string? opinion, string? text)
        {
            var (a, who, deny) = await KretsActionAsync(id);
            if (deny != null) return deny;
            var (saved, err) = _apps.Opinion(id, opinion ?? "", text, who!);
            if (saved == null) return Json(new { success = false, message = err });
            _calendar.Invalidate();
            var tillstyrker = saved.KretsOpinion == CompetitionApplicationOpinion.Tillstyrker;
            var n = await NotifyClubAsync(saved, who!,
                $"Kretsen {(tillstyrker ? "tillstyrker" : "avstyrker")}: {saved.Name}",
                new[] { $"{RegionName(saved.RegionId)} {(tillstyrker ? "tillstyrker" : "avstyrker")} ansökan om {saved.Name} och skickar den vidare till Förbundet, som beslutar.",
                        saved.KretsOpinionText ?? "",
                        tillstyrker ? "Ni kan redan nu skapa tävlingen och börja med inbjudan: Administration → Tävlingar → Ansökningar → Skapa tävlingen. Den markeras då som väntande på Förbundet." : "" });
            return Json(new { success = true, notified = n, message = MailMessage(n, "Yttrandet är registrerat") });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterForbundetDecision(int id, string? decision, string? decisionDate, string? grantedDate, string? text)
        {
            var (a, who, deny) = await KretsActionAsync(id, allowHosForbundet: true);
            if (deny != null) return deny;
            var granted = decision == "granted";
            if (!granted && decision != "rejected") return Json(new { success = false, message = "Okänt beslut." });
            var dd = ParseDate(decisionDate) ?? DateTime.Today;
            var (saved, err) = _apps.RegisterForbundetDecision(id, granted, dd, ParseDate(grantedDate), text, who!);
            if (saved == null) return Json(new { success = false, message = err });
            _calendar.Invalidate();
            var moved = saved.GrantedDate.HasValue ? $" Förbundet har beviljat den {saved.GrantedDate:yyyy-MM-dd} i stället för {saved.CompetitionDate:yyyy-MM-dd}." : "";
            var hasComp = saved.CompetitionId is > 0;
            var n = await NotifyClubAsync(saved, who!,
                granted ? $"Förbundet har beviljat: {saved.Name}" : $"Förbundet har avslagit: {saved.Name}",
                new[] { granted ? $"Förbundet har beviljat ansökan om {saved.Name}.{moved}" : $"Förbundet har avslagit ansökan om {saved.Name}.",
                        saved.DecisionText ?? "",
                        granted && hasComp && saved.GrantedDate.HasValue ? "Tävlingen ni redan skapat har kvar det gamla datumet. Ändra det i tävlingens redigering." : "",
                        !granted && hasComp ? "Tävlingen ni redan skapat finns kvar. Ta bort den, eller gör om den till en kretstävling efter samråd med kretsen." : "" });
            return Json(new { success = true, notified = n, message = MailMessage(n, "Förbundets beslut är registrerat") });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkSentToForbundet(int regionId, string? ids)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var me = await CurrentMemberAsync();
            var idList = (ids ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(s => int.TryParse(s, out var i) ? i : 0).Where(i => i > 0)
                .Where(i => _apps.Get(i)?.RegionId == regionId).ToList();
            var n = _apps.MarkSentToForbundet(idList, me?.Id ?? 0, me == null ? "" : DisplayName(me));
            return Json(new { success = true, marked = n, message = $"{n} {(n == 1 ? "ansökan" : "ansökningar")} markerade som skickade till Förbundet." });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetDeadline(int regionId, int year, string? level, string? lastDate)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var d = string.IsNullOrWhiteSpace(lastDate) ? null : ParseDate(lastDate);
            if (!string.IsNullOrWhiteSpace(lastDate) && d == null) return Json(new { success = false, message = "Ogiltigt datum." });
            var err = _apps.SetDeadline(regionId, year, level ?? "", d);
            return Json(err == null ? new { success = true, message = d == null ? "Sista dagen borttagen." : "Sista dagen sparad." } : new { success = false, message = err });
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  Länkläget
        // ════════════════════════════════════════════════════════════════════════════════

        /// <summary>Ett ärende via länk utan inloggning. Visar bara det som behövs för beslutet.</summary>
        [HttpGet]
        public IActionResult GetCaseByLink(string t)
        {
            var (a, link, error) = ReadCaseLink(t);
            if (a == null) return Json(new { success = false, message = error });
            var year = DateTime.Today.Year;
            var viaLinkThisYear = SafeList(() => _apps.ForRegion(a.RegionId))
                .Count(x => x.Channel == KretsChannel.Lank && x.DecidedAt.HasValue && x.DecidedAt.Value.Year == year
                            || x.Channel == KretsChannel.Lank && x.Status == CompetitionApplicationStatus.HosForbundet && x.UpdatedAt.Year == year);
            return Json(new
            {
                success = true,
                application = Dto(a, forClub: false),
                canAct = CompetitionApplicationRules.KretsCanAct(a.Status),
                viaLinkThisYear,
                region = _calendar.Region(a.RegionId) is { } r ? new { r.Id, r.Name } : null
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ActByLink(string t, string? action, string? text, string? name, string? role)
        {
            var (a, link, error) = ReadCaseLink(t);
            if (a == null) return Json(new { success = false, message = error });
            name = Clip(name, 200);
            role = Clip(role, 200);
            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(role))
                return Json(new { success = false, message = "Skriv ditt namn och din roll i kretsen — de står med på beslutet." });

            var who = new KretsDecider(0, name!, role!, KretsChannel.Lank, link!.SentTo);
            (CompetitionApplication? saved, string? err) r = action switch
            {
                "approve" => _apps.Decide(a.Id, true, text, who),
                "reject" => _apps.Decide(a.Id, false, text, who),
                "complete" => _apps.RequestCompletion(a.Id, text ?? "", who),
                "tillstyrk" => _apps.Opinion(a.Id, CompetitionApplicationOpinion.Tillstyrker, text, who),
                "avstyrk" => _apps.Opinion(a.Id, CompetitionApplicationOpinion.Avstyrker, text, who),
                _ => (null, "Okänd åtgärd.")
            };
            if (r.saved == null) return Json(new { success = false, message = r.err });
            _calendar.Invalidate();

            var subject = action switch
            {
                "approve" => $"Godkänd: {r.saved.Name}",
                "reject" => $"Avslagen: {r.saved.Name}",
                "complete" => $"Kretsen ber om komplettering: {r.saved.Name}",
                _ => $"Kretsens yttrande: {r.saved.Name}"
            };
            var text1 = action switch
            {
                "approve" => $"{RegionName(r.saved.RegionId)} har godkänt ansökan om {r.saved.Name} ({name}, {role}).",
                "reject" => $"{RegionName(r.saved.RegionId)} har avslagit ansökan om {r.saved.Name} ({name}, {role}).",
                "complete" => $"{name} ({role}) i {RegionName(r.saved.RegionId)} ber er komplettera ansökan om {r.saved.Name}:",
                _ => $"{RegionName(r.saved.RegionId)} {(action == "tillstyrk" ? "tillstyrker" : "avstyrker")} ansökan om {r.saved.Name} ({name}, {role}). Förbundet beslutar."
            };
            var n = await NotifyClubAsync(r.saved, who, subject, new[] { text1, text ?? "" });
            return Json(new { success = true, notified = n, message = "Tack. Beslutet är registrerat och klubben har fått besked." + (n == 0 ? " (Mejlet till klubben kunde inte skickas.)" : "") });
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  "Be kretsen komma igång"
        // ════════════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Arrangörens färdiga, redigerbara mejl till kretsens ordförande (annars kontaktadressen):
        /// utse en tävlingsansvarig, så går det fortare nästa gång. Svarsadress = arrangören.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AskKretsToStart(int clubId, string? text)
        {
            if (!await _auth.IsClubAdminForClub(clubId)) return Json(new { success = false, message = "Åtkomst nekad" });
            var me = await CurrentMemberAsync();
            if (me == null) return Json(new { success = false, message = "Logga in först." });
            var regionId = _calendar.RegionIdForClub(clubId);
            var region = _calendar.Region(regionId);
            if (region == null) return Json(new { success = false, message = "Klubbens krets hittades inte." });
            text = Clip(text, 3000);
            if (string.IsNullOrWhiteSpace(text)) return Json(new { success = false, message = "Mejlet är tomt." });

            var recipients = new List<(string Email, string Name)>();
            foreach (var r in _roles.GetActiveRoleHolders(DocumentOwnerType.Region, regionId, BoardRoleDefinitions.RoleOrdforande))
            {
                var m = _memberService.GetById(r.MemberId);
                if (!string.IsNullOrWhiteSpace(m?.Email)) recipients.Add((m!.Email, r.MemberName ?? ""));
            }
            if (recipients.Count == 0)
            {
                var contact = KretsContact(regionId);
                if (!string.IsNullOrWhiteSpace(contact)) recipients.Add((contact!, region.Name));
            }
            if (recipients.Count == 0)
                return Json(new { success = false, message = $"{region.Name} har varken ordförande eller kontaktadress på pistol.nu. Kontakta kretsen på annat sätt." });

            var url = $"{Request.Scheme}://{Request.Host}/kretsen/kom-igang?krets={region.Id}";
            var clubName = _clubs.GetClubNameById(clubId) ?? "";
            int sent = 0;
            foreach (var (email, name) in recipients)
                if (await _email.SendKretsgranskningAsync(email, name, $"{clubName}: kom igång med pistol.nu i {region.Name}",
                        new[] { text!, }, "Kom igång", url,
                        $"Skickat av {DisplayName(me)}, {clubName}, via pistol.nu. Svarar du på mejlet når du {DisplayName(me)}.",
                        _replyTo.ForPersonInClub(me.Id, clubId)))
                    sent++;
            return Json(new { success = sent > 0, sent, message = sent > 0 ? $"Mejlet är skickat till {string.Join(", ", recipients.Select(r => r.Name))}." : "Mejlet kunde inte skickas." });
        }

        /// <summary>
        /// Supportväg: kör påminnelsevarvet nu (annars var 12:e timme). Bara sajtadmin. Spärren
        /// mot dubbletter är densamma — ett andra varv skickar ingenting som redan gått ut.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RunRemindersNow()
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Åtkomst nekad" });
            var svc = HttpContext.RequestServices.GetServices<Microsoft.Extensions.Hosting.IHostedService>()
                .OfType<CompetitionApplicationReminderHostedService>().FirstOrDefault();
            if (svc == null) return Json(new { success = false, message = "Påminnelsetjänsten är inte registrerad." });
            var n = await svc.RunOnceAsync(DateTime.Today);
            return Json(new { success = true, sent = n });
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  Kalendern (öppen)
        // ════════════════════════════════════════════════════════════════════════════════

        [HttpGet]
        public async Task<IActionResult> GetCalendar(int regionId, string? from, string? to, bool neighbours = false, string? mode = null)
        {
            var region = _calendar.Region(regionId);
            if (region == null) return Json(new { success = false, message = "Kretsen hittades inte." });
            // Två lägen (Stefans beslut 2026-10-02): den PUBLIKA kalendern på kretssidan och
            // PLANERINGSkalendern i krets- och klubbadmin. Planeringen visar preliminära ansökningar,
            // stomprogrammet och krockar, och kräver att besökaren administrerar kretsen eller en klubb i den.
            var planning = string.Equals(mode, "planning", StringComparison.OrdinalIgnoreCase);
            if (planning && !await CanPlanAsync(regionId))
                return Json(new { success = false, message = "Planeringskalendern är för kretsens och klubbarnas administratörer." });
            var f = ParseDate(from) ?? new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1);
            var tt = ParseDate(to) ?? f.AddMonths(1).AddDays(-1);
            if ((tt - f).TotalDays > 400) tt = f.AddDays(400);   // en sida ska inte kunna be om hela historiken

            var viewerIsAdmin = planning || await ViewerIsAdminAsync();
            var entries = _calendar.Build(regionId, f, tt, neighbours, viewerIsAdmin, planning);

            // Kan besökaren ansöka här? Klubbarna i kretsen där hen är admin, och kretsen själv. Bara i planeringen.
            var applyClubs = new List<object>();
            var me = await CurrentMemberAsync();
            if (me != null && planning)
            {
                foreach (var (cid, cname) in _calendar.ClubsInRegion(regionId).OrderBy(c => c.Value))
                    if (await ClubAdminDirectAsync(me.Id, cid)) applyClubs.Add(new { id = cid, name = cname });
            }
            var canApplyAsRegion = planning && me != null && await _auth.IsRegionalAdminForRegion(region.Code);

            return Json(new
            {
                success = true,
                region = new { region.Id, region.Code, region.Name },
                from = f.ToString("yyyy-MM-dd"),
                to = tt.ToString("yyyy-MM-dd"),
                neighbours = _calendar.Neighbours(regionId).Select(n => n.Name),
                entries = entries.Select(e => new
                {
                    e.Kind, e.Id, e.Name,
                    date = e.Date.ToString("yyyy-MM-dd"),
                    endDate = e.EndDate?.ToString("yyyy-MM-dd"),
                    e.Discipline, e.DisciplineLabel,
                    levelLabel = string.IsNullOrEmpty(e.Level) ? "" : CompetitionLevel.Find(e.Level)?.ShortLabel ?? "",
                    e.Organiser, e.Place, e.Url, e.Status, e.StatusLabel, e.RegionName, e.IsNeighbour, e.IsSm, e.IsPeriod, e.Conflicts
                }),
                applyClubs,
                canApplyAsRegion,
                planning
            });
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  Fas 4, resten: grannkretsar, arrangörschecklista, Förbundets stomprogram
        // ════════════════════════════════════════════════════════════════════════════════

        /// <summary>Kretsens grannkretsar: alla kretsar, vilka som är valda, och vilka som är standarden.</summary>
        [HttpGet]
        public async Task<IActionResult> GetNeighbourSettings(int regionId)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var region = _calendar.Region(regionId)!;
            var overrides = SafeSettings(regionId)?.NeighbourOverrides;
            var chosen = RegionNeighbourSetting.Resolve(region.Code, overrides).ToHashSet(StringComparer.OrdinalIgnoreCase);
            var standard = HpskSite.Models.RegionAdjacency.NeighboursOf(region.Code);
            return Json(new
            {
                success = true,
                isDefault = overrides == null,
                regions = _calendar.AllRegions().Where(r => r.Id != regionId).Select(r => new
                {
                    r.Code, r.Name,
                    chosen = chosen.Contains(r.Code),
                    standard = standard.Contains(r.Code)
                })
            });
        }

        /// <summary>Sparar kretsens val. <paramref name="useDefault"/> = "1" tar bort valet (standarden gäller).</summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveNeighbours(int regionId, string? codes, string? useDefault)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var region = _calendar.Region(regionId)!;
            var known = _calendar.AllRegions().Select(r => r.Code).ToHashSet(StringComparer.OrdinalIgnoreCase);
            var list = (codes ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
            var unknown = list.Where(c => !known.Contains(c)).ToList();
            if (unknown.Count > 0) return Json(new { success = false, message = "Okänd krets: " + string.Join(", ", unknown) });
            var me = await CurrentMemberAsync();
            var s = SafeSettings(regionId) ?? new RegionCalendarSettings { RegionId = regionId };
            s.NeighbourOverrides = useDefault == "1" ? null : RegionNeighbourSetting.ToStored(region.Code, list);
            _apps.SaveSettings(s, me?.Id ?? 0);
            var n = RegionNeighbourSetting.Resolve(region.Code, s.NeighbourOverrides).Count;
            return Json(new
            {
                success = true,
                message = s.NeighbourOverrides == null
                    ? $"Sparat. Kretsen använder standardgrannarna ({n} kretsar)."
                    : n == 0 ? "Sparat. Kretsen har inga grannkretsar i kalendern." : $"Sparat. {n} grannkretsar visas i kalendern och används för krockvarningar."
            });
        }

        // ── Arrangörschecklistan ───────────────────────────────────────────────────────────

        [HttpGet]
        public async Task<IActionResult> GetOrganiserChecklist(int regionId)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var planning = HttpContext.RequestServices.GetRequiredService<KretsPlanningService>();
            if (!planning.TablesExist()) return Json(new { success = false, message = "Checklistans tabeller saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            return Json(new
            {
                success = true,
                scopes = OrganiserChecklistScope.Values.Select(v => new { value = v, label = OrganiserChecklistScope.Label(v) }),
                items = planning.Checklist(regionId).Select(ChecklistDto)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveOrganiserChecklistItem(int regionId, int id, string? title, string? description, string? daysBeforeComp, string? appliesTo)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            int? days = null;
            if (!string.IsNullOrWhiteSpace(daysBeforeComp))
            {
                if (!int.TryParse(daysBeforeComp.Trim(), out var d)) return Json(new { success = false, message = "Antalet dagar ska vara ett heltal." });
                days = d;
            }
            var me = await CurrentMemberAsync();
            var planning = HttpContext.RequestServices.GetRequiredService<KretsPlanningService>();
            var (item, err) = planning.SaveChecklistItem(regionId, id, title, description, days, appliesTo, me?.Id ?? 0);
            return Json(item == null ? new { success = false, message = err } : (object)new { success = true, item = ChecklistDto(item) });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveOrganiserChecklistItem(int regionId, int id)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var ok = HttpContext.RequestServices.GetRequiredService<KretsPlanningService>().RemoveChecklistItem(regionId, id);
            return Json(new { success = ok, message = ok ? "Punkten är borttagen. Uppgifter som redan lagts in i tävlingarnas förberedelser står kvar." : "Punkten finns inte." });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MoveOrganiserChecklistItem(int regionId, int id, int direction)
        {
            var auth = await KretsAuthorityAsync(regionId);
            if (!auth.Allowed) return Json(new { success = false, message = "Åtkomst nekad" });
            var ok = HttpContext.RequestServices.GetRequiredService<KretsPlanningService>().MoveChecklistItem(regionId, id, direction);
            return Json(new { success = ok });
        }

        private static object ChecklistDto(RegionOrganiserChecklistItem i) => new
        {
            i.Id, i.Title, i.Description, i.DaysBeforeComp, appliesTo = OrganiserChecklistScope.Normalize(i.AppliesTo),
            appliesToLabel = OrganiserChecklistScope.Label(i.AppliesTo),
            whenLabel = i.DaysBeforeComp == null ? "" : i.DaysBeforeComp == 0 ? "på tävlingsdagen"
                : i.DaysBeforeComp > 0 ? $"{i.DaysBeforeComp} dagar före" : $"{-i.DaysBeforeComp} dagar efter"
        };

        // ── Förbundets stomprogram (sajtadmin) ─────────────────────────────────────────────

        [HttpGet]
        public async Task<IActionResult> GetStomprogram(int year)
        {
            // Läsbart för inloggade: kalendrarna visar programmet för kretsens och klubbarnas
            // administratörer, och ytan där det förs in är sajtadministratörens.
            if (await CurrentMemberAsync() == null) return Json(new { success = false, message = "Logga in för att se stomprogrammet." });
            var stom = HttpContext.RequestServices.GetRequiredService<StomprogramService>();
            if (!stom.TableExists()) return Json(new { success = false, message = "Stomprogrammets tabell saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            if (year < 2000 || year > 2100) year = DateTime.Today.Year;
            return Json(new
            {
                success = true,
                year,
                canEdit = await _auth.IsCurrentUserAdminAsync(),
                disciplines = StomprogramDisciplineOptions(),
                items = stom.Year(year).Select(StomDto)
            });
        }

        private static object StomDto(StomprogramItem s) => new
        {
            s.Id, s.Name, s.Note, s.IsPeriod,
            start = s.StartDate.ToString("yyyy-MM-dd"), end = s.EndDate?.ToString("yyyy-MM-dd"),
            discipline = s.Discipline ?? "",
            disciplineLabel = StomprogramDisciplines.Label(s.Discipline)
        };

        private static IEnumerable<object> StomprogramDisciplineOptions() =>
            new[] { new { id = "", name = "Alla grener" } }
                .Concat(HpskSite.Models.CompetitionTypes.All.Select(t => new { id = t.Id, name = t.Name }))
                .Append(new { id = StomprogramDisciplines.Other, name = "Annan gren (krockar inte)" });

        /// <summary>Förbundets egen webbplats — den enda värd hämtningen får gå till.</summary>
        private static bool IsForbundetUrl(Uri u) =>
            u.Scheme == Uri.UriSchemeHttps
            && (u.Host.Equals("www.pistolskytteforbundet.se", StringComparison.OrdinalIgnoreCase)
                || u.Host.Equals("pistolskytteforbundet.se", StringComparison.OrdinalIgnoreCase));

        /// <summary>
        /// Läser Förbundets stomprogramsida som UNDERLAG. Sparar ingenting: svaret är raderna, med
        /// vilka som redan finns, och sajtadmin väljer vad som läggs in. ⚠️ Bara Förbundets värd —
        /// en hämtning åt en användare till en godtycklig adress är en öppning in i vårt eget nät.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FetchStomprogramFromForbundet(string? url, int? year)
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Bara sajtadministratören för in Förbundets stomprogram." });
            var stom = HttpContext.RequestServices.GetRequiredService<StomprogramService>();
            if (!stom.TableExists()) return Json(new { success = false, message = "Stomprogrammets tabell saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            if (!Uri.TryCreate((url ?? "").Trim(), UriKind.Absolute, out var uri) || !IsForbundetUrl(uri))
                return Json(new { success = false, message = "Ange en adress på https://www.pistolskytteforbundet.se/." });

            string html;
            try
            {
                var http = HttpContext.RequestServices.GetRequiredService<IHttpClientFactory>().CreateClient("Forbundet");
                // Omdirigeringar följs för hand, så att varje steg prövas mot värden.
                HttpResponseMessage? resp = null;
                for (var hop = 0; hop < 4; hop++)
                {
                    resp?.Dispose();
                    resp = await http.GetAsync(uri, HttpCompletionOption.ResponseHeadersRead);
                    if ((int)resp.StatusCode is >= 300 and < 400 && resp.Headers.Location != null)
                    {
                        var next = resp.Headers.Location.IsAbsoluteUri ? resp.Headers.Location : new Uri(uri, resp.Headers.Location);
                        if (!IsForbundetUrl(next)) return Json(new { success = false, message = "Förbundets sida skickade vidare till en annan webbplats. Ingenting lästes in." });
                        uri = next;
                        continue;
                    }
                    break;
                }
                using (resp)
                {
                    if (resp == null || !resp.IsSuccessStatusCode)
                        return Json(new { success = false, message = $"Förbundets sida svarade {(int?)resp?.StatusCode}. Kontrollera adressen." });
                    if (resp.Content.Headers.ContentLength > 3_000_000)
                        return Json(new { success = false, message = "Sidan är för stor för att vara ett stomprogram." });
                    html = await resp.Content.ReadAsStringAsync();
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Stomprogrammet kunde inte hämtas från {Url}.", uri);
                return Json(new { success = false, message = "Förbundets sida gick inte att nå. Försök igen, eller klistra in raderna för hand." });
            }

            var parsed = StomprogramHtmlImport.Parse(html, year);
            var existing = parsed.Year is int y ? stom.Year(y) : new List<StomprogramItem>();
            return Json(new
            {
                success = true,
                year = parsed.Year,
                source = uri.ToString(),
                warnings = parsed.Warnings,
                disciplines = StomprogramDisciplineOptions(),
                rows = parsed.Rows.Select(r => new
                {
                    r.Number, r.Name, r.Note, r.IsPeriod, r.Problem, r.Source,
                    start = r.Start?.ToString("yyyy-MM-dd"), end = r.End?.ToString("yyyy-MM-dd"),
                    discipline = r.Discipline ?? "",
                    disciplineLabel = StomprogramDisciplines.Label(r.Discipline),
                    existsAs = r.Start is DateTime s ? StomprogramService.FindDuplicate(existing, s, r.End, r.Name, r.Discipline)?.Name : null
                })
            });
        }

        public class StomprogramRowInput
        {
            public string? Start { get; set; }
            public string? End { get; set; }
            public string? Name { get; set; }
            public string? Discipline { get; set; }
            public string? Note { get; set; }
            public bool IsPeriod { get; set; }
        }

        /// <summary>Prövar en rad; null = giltig, annars skälet.</summary>
        private static string? ValidateStomRow(StomprogramRowInput r, out DateTime start, out DateTime? end)
        {
            end = null;
            if (!DateTime.TryParseExact(r.Start ?? "", "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out start))
                return "startdatumet saknas eller går inte att läsa";
            if (!string.IsNullOrWhiteSpace(r.End))
            {
                if (!DateTime.TryParseExact(r.End, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var e))
                    return "slutdatumet går inte att läsa";
                if (e < start) return "slutdatumet ligger före startdatumet";
                if (e > start) end = e;
            }
            var name = (r.Name ?? "").Trim();
            if (name.Length == 0) return "namnet saknas";
            if (name.Length > 200) return "namnet är längre än 200 tecken";
            if (!StomprogramDisciplines.IsValid(r.Discipline)) return $"grenen \"{r.Discipline}\" finns inte";
            if ((r.Note ?? "").Length > 500) return "anteckningen är längre än 500 tecken";
            return null;
        }

        /// <summary>
        /// Lägger in de rader sajtadmin markerat i förhandsvisningen. Rader som redan finns hoppas över
        /// och räknas. En ogiltig rad stoppar inläsningen — samma regel som inklistringen.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ImportStomprogram(string? rowsJson)
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Bara sajtadministratören för in Förbundets stomprogram." });
            var stom = HttpContext.RequestServices.GetRequiredService<StomprogramService>();
            if (!stom.TableExists()) return Json(new { success = false, message = "Stomprogrammets tabell saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            List<StomprogramRowInput>? rows;
            try { rows = System.Text.Json.JsonSerializer.Deserialize<List<StomprogramRowInput>>(rowsJson ?? "[]", new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true }); }
            catch { return Json(new { success = false, message = "Raderna gick inte att läsa." }); }
            if (rows == null || rows.Count == 0) return Json(new { success = false, message = "Markera minst en rad." });
            if (rows.Count > 300) return Json(new { success = false, message = "För många rader på en gång." });

            var errors = new List<string>();
            var ok = new List<(StomprogramRowInput Row, DateTime Start, DateTime? End)>();
            for (var i = 0; i < rows.Count; i++)
            {
                var why = ValidateStomRow(rows[i], out var s, out var e);
                if (why != null) errors.Add($"Rad {i + 1} ({rows[i].Name}): {why}.");
                else ok.Add((rows[i], s, e));
            }
            if (errors.Count > 0) return Json(new { success = false, message = "Ingenting lades in.", errors });

            var me = await CurrentMemberAsync();
            var existingByYear = new Dictionary<int, List<StomprogramItem>>();
            int added = 0, skipped = 0;
            foreach (var (r, s, e) in ok)
            {
                if (!existingByYear.TryGetValue(s.Year, out var existing)) existingByYear[s.Year] = existing = stom.Year(s.Year);
                var disc = string.IsNullOrWhiteSpace(r.Discipline) ? null : r.Discipline;
                if (StomprogramService.FindDuplicate(existing, s, e, r.Name!, disc) != null) { skipped++; continue; }
                existing.Add(stom.Add(s, e, r.Name!, disc, r.Note, me?.Id ?? 0, r.IsPeriod));
                added++;
            }
            _calendar.Invalidate();
            var msg = $"{added} {(added == 1 ? "rad" : "rader")} inlagda i stomprogrammet."
                + (skipped > 0 ? $" {skipped} fanns redan och hoppades över." : "");
            return Json(new { success = true, added, skipped, message = msg });
        }

        /// <summary>Lägger till (id = 0) eller rättar en rad i stomprogrammet.</summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveStomprogram(int id, StomprogramRowInput row)
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Bara sajtadministratören för in Förbundets stomprogram." });
            var stom = HttpContext.RequestServices.GetRequiredService<StomprogramService>();
            if (!stom.TableExists()) return Json(new { success = false, message = "Stomprogrammets tabell saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            var why = ValidateStomRow(row, out var s, out var e);
            if (why != null) return Json(new { success = false, message = char.ToUpper(why[0]) + why[1..] + "." });
            var disc = string.IsNullOrWhiteSpace(row.Discipline) ? null : row.Discipline;
            if (id > 0)
            {
                if (stom.Get(id) == null) return Json(new { success = false, message = "Raden finns inte." });
                stom.Update(id, s, e, row.Name!, disc, row.Note, row.IsPeriod);
            }
            else
            {
                var me = await CurrentMemberAsync();
                id = stom.Add(s, e, row.Name!, disc, row.Note, me?.Id ?? 0, row.IsPeriod).Id;
            }
            _calendar.Invalidate();
            return Json(new { success = true, item = StomDto(stom.Get(id)!), message = "Sparat." });
        }

        /// <summary>
        /// Lägger till rader i stomprogrammet — inklistrade (<c>datum; namn; gren</c>). Ingenting sparas
        /// om någon rad inte går att läsa: en halvt inläst lista är svår att rätta.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStomprogram(string? text)
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Bara sajtadministratören för in Förbundets stomprogram." });
            var stom = HttpContext.RequestServices.GetRequiredService<StomprogramService>();
            if (!stom.TableExists()) return Json(new { success = false, message = "Stomprogrammets tabell saknas. Kör Migrations/create-kretsplanering-tables.sql." });
            var parsed = StomprogramPaste.Parse(text, ResolveDisciplineWord);
            if (parsed.Errors.Count > 0) return Json(new { success = false, message = "Ingenting sparades.", errors = parsed.Errors });
            if (parsed.Rows.Count == 0) return Json(new { success = false, message = "Inga rader att lägga till." });
            var me = await CurrentMemberAsync();
            foreach (var r in parsed.Rows) stom.Add(r.Start, r.End, r.Name, r.Discipline, null, me?.Id ?? 0);
            _calendar.Invalidate();
            return Json(new { success = true, added = parsed.Rows.Count, message = $"{parsed.Rows.Count} {(parsed.Rows.Count == 1 ? "rad" : "rader")} tillagda i stomprogrammet." });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStomprogram(int id)
        {
            if (!await _auth.IsCurrentUserAdminAsync()) return Json(new { success = false, message = "Åtkomst nekad" });
            var ok = HttpContext.RequestServices.GetRequiredService<StomprogramService>().Delete(id);
            if (ok) _calendar.Invalidate();
            return Json(new { success = ok, message = ok ? "Raden är borttagen." : "Raden finns inte." });
        }

        /// <summary>Grenens id ur ett ord i en inklistrad rad: id, visningsnamn eller ett vardagsord.</summary>
        private static string? ResolveDisciplineWord(string word)
        {
            var c = ActivityDiscipline.Canonical(word);
            if (c.Length > 0) return c;
            return word.Trim().ToLowerInvariant() switch
            {
                "fält" or "falt" or "fältskytte" => "Faltskytte",
                "magnumfält" or "magnum fält" => "MagnumFalt",
                "spring" => "Springskytte",
                "helmatch" or "nationell helmatch" => "NationellHelmatch",
                _ => null
            };
        }

        private RegionCalendarSettings? SafeSettings(int regionId)
        {
            try { return _apps.Settings(regionId); }
            catch (Exception ex) { _logger.LogWarning(ex, "Kretsens inställningar kunde inte läsas för {Region}.", regionId); return null; }
        }

        // ════════════════════════════════════════════════════════════════════════════════
        //  Internt
        // ════════════════════════════════════════════════════════════════════════════════

        private object Dto(CompetitionApplication a, bool forClub) => new
        {
            a.Id, a.RegionId, a.ClubId,
            clubName = a.ClubId > 0 ? (_clubs.GetClubNameById(a.ClubId) ?? "") : RegionName(a.RegionId),
            regionName = RegionName(a.RegionId),
            a.Level, levelLabel = CompetitionLevel.Find(a.Level)?.Label ?? a.Level,
            a.Discipline, disciplineLabel = ActivityDiscipline.Label(a.Discipline),
            a.Name,
            competitionDate = a.CompetitionDate.ToString("yyyy-MM-dd"),
            endDate = a.EndDate?.ToString("yyyy-MM-dd"),
            reserveDate = a.ReserveDate?.ToString("yyyy-MM-dd"),
            grantedDate = a.GrantedDate?.ToString("yyyy-MM-dd"),
            a.RangeId, a.Place, a.ContactName, a.ContactEmail, a.ContactPhone, a.Classes, a.Note,
            a.Status, statusLabel = CompetitionApplicationStatus.Label(a.Status),
            a.KretsOpinion, a.KretsOpinionText, a.CompletionRequest, a.CompletionReply, a.DecisionText,
            decidedAt = a.DecidedAt?.ToString("yyyy-MM-dd"),
            a.DeciderName, a.DeciderRole, a.Channel,
            sentToForbundetAt = a.SentToForbundetAt?.ToString("yyyy-MM-dd"),
            a.CompetitionId,
            competitionUrl = a.CompetitionId is > 0 ? CompetitionUrl(a.CompetitionId.Value) : null,
            submittedAt = a.SubmittedAt?.ToString("yyyy-MM-dd"),
            needsForbundet = a.NeedsForbundet,
            canEdit = forClub && CompetitionApplicationRules.ClubCanEdit(a.Status),
            canSubmit = forClub && CompetitionApplicationRules.ClubCanSubmit(a.Status),
            canWithdraw = forClub && CompetitionApplicationRules.ClubCanWithdraw(a.Status) && a.CompetitionId is null or <= 0,
            canReply = forClub && a.Status == CompetitionApplicationStatus.Komplettering,
            canCreateCompetition = forClub && CompetitionApplicationRules.CanCreateCompetition(a),
            lateNote = LateNote(a)
        };

        private string? CompetitionUrl(int id)
        {
            try
            {
                var c = UmbracoContext.Content?.GetById(id);
                return c == null ? null : HpskSite.Extensions.CompetitionUrlExtensions.CompetitionUrl(c);
            }
            catch { return null; }
        }

        /// <summary>Om ansökan kom (eller skulle komma) efter kretsens sista dag eller Förbundets gräns.</summary>
        private string? LateNote(CompetitionApplication a)
        {
            var when = a.SubmittedAt ?? DateTime.Today;
            if (a.NeedsForbundet && CompetitionApplicationRules.IsLate(when, CompetitionApplicationRules.ForbundetDeadline(a.CompetitionDate.Year)))
                return $"Förbundets sista dag för {a.CompetitionDate.Year} var {CompetitionApplicationRules.ForbundetDeadline(a.CompetitionDate.Year).ToString("d MMMM yyyy", new CultureInfo("sv-SE"))}. Kretsen kan skicka den som komplettering.";
            DateTime? last = null;
            try { last = _apps.DeadlineFor(a.RegionId, a.CompetitionDate.Year, a.Level); } catch { }
            if (last.HasValue && CompetitionApplicationRules.IsLate(when, last.Value))
                return $"Kretsens sista ansökningsdag var {last.Value.ToString("d MMMM yyyy", new CultureInfo("sv-SE"))}.";
            return null;
        }

        /// <summary>
        /// Aviserar kretsen. Med en tävlingsansvarig: personerna, med en knapp till inkorgen. Utan:
        /// länkläget — kretsens kontaktadress får en länk som fungerar utan inloggning, och
        /// kretsadministratörerna (inloggade) får inkorgen.
        /// </summary>
        private async Task<int> NotifyKretsAsync(CompetitionApplication a, Umbraco.Cms.Core.Models.IMember actor, string headline)
        {
            try
            {
                var rec = _uppdrag.Recipients(a.RegionId, BoardRoleDefinitions.RoleTavlingsansvarig);
                var base_ = $"{Request.Scheme}://{Request.Host}";
                var inbox = $"{base_}/kretsen/ansokningar?krets={a.RegionId}";
                var club = a.ClubId > 0 ? (_clubs.GetClubNameById(a.ClubId) ?? "") : RegionName(a.RegionId);
                var level = CompetitionLevel.Find(a.Level)?.Label?.ToLowerInvariant() ?? a.Level;
                var paras = new List<string>
                {
                    $"{club} ansöker om att arrangera {a.Name} ({level}, {ActivityDiscipline.Label(a.Discipline).ToLowerInvariant()}) den {a.CompetitionDate:yyyy-MM-dd}.",
                    string.IsNullOrWhiteSpace(a.Place) ? "" : $"Plats: {a.Place}",
                    string.IsNullOrWhiteSpace(a.Note) ? "" : $"Meddelande: {a.Note}",
                    a.Status == CompetitionApplicationStatus.Inskickad && !string.IsNullOrEmpty(a.CompletionReply) ? $"Klubbens komplettering: {a.CompletionReply}" : "",
                    a.NeedsForbundet ? "En nationell tävling och en landsdelstävling beslutas av Förbundet. Kretsen tillstyrker eller avstyrker, och ansökan kommer med i kretsens sammanställning." : "Kretsen beslutar själv om en kretstävling."
                };
                var replyTo = _replyTo.ForPersonInClub(actor.Id, a.ClubId);
                int sent = 0;
                foreach (var r in rec.To)
                {
                    string url, btn, notice;
                    if (r.MemberId > 0)
                    {
                        url = inbox; btn = "Öppna kretsens ansökningar";
                        notice = rec.IsFallback
                            ? "Du får mejlet för att du är kretsadministratör och kretsen inte har utsett någon tävlingsansvarig."
                            : "Du får mejlet för att du är kretsens tävlingsansvarige.";
                    }
                    else
                    {
                        var token = _tokens.CreateCaseLink(CaseKind, a.Id, a.RegionId, Checksum(a), r.Email);
                        url = $"{base_}/kretsen/arende?t={Uri.EscapeDataString(token)}"; _caseLinks.Add(url); btn = "Granska ansökan";
                        notice = $"Kretsen har inte utsett någon tävlingsansvarig på pistol.nu, så ansökan kommer som en länk som fungerar utan inloggning i 60 dagar. "
                               + $"Utser kretsen någon hamnar nästa ansökan direkt hos den personen: {base_}/kretsen/kom-igang?krets={a.RegionId}";
                        try { _apps.SetLinkSentTo(a.Id, r.Email); } catch { }
                    }
                    if (await _email.SendKretsgranskningAsync(r.Email, r.Name, $"{headline}: {a.Name}", paras, btn, url, notice, replyTo))
                        sent++;
                }
                return sent;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Ansökan {Id}: kretsen kunde inte aviseras.", a.Id);
                return 0;
            }
        }

        /// <summary>Besked till klubben: ansökans kontakt, klubbens kontaktadress och den som skapade den.</summary>
        private async Task<int> NotifyClubAsync(CompetitionApplication a, KretsDecider who, string subject, IEnumerable<string> paras)
        {
            try
            {
                var to = new List<(string Email, string Name)>();
                var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                void Add(string? e, string n) { if (!string.IsNullOrWhiteSpace(e) && seen.Add(e.Trim())) to.Add((e.Trim(), n)); }
                Add(a.ContactEmail, a.ContactName ?? "");
                var creator = _memberService.GetById(a.CreatedByMemberId);
                if (creator != null) Add(creator.Email, DisplayName(creator));
                if (a.ClubId > 0) Add(_clubs.GetClubById(a.ClubId)?.ContactEmail, _clubs.GetClubNameById(a.ClubId) ?? "");

                var replyTo = who.MemberId > 0 ? _replyTo.ForMember(who.MemberId) : _replyTo.ForRegion(a.RegionId);
                int sent = 0;
                foreach (var (email, name) in to)
                    if (await _email.SendKretsgranskningAsync(email, name, subject, paras, null, null,
                            $"Beslutet fattades av {who.Name} ({who.Role}).", replyTo))
                        sent++;
                return sent;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Ansökan {Id}: klubben kunde inte aviseras.", a.Id);
                return 0;
            }
        }

        public static string Checksum(CompetitionApplication a) => CompetitionApplicationRules.Checksum(a);

        private (CompetitionApplication? App, CaseLinkPayload? Link, string? Error) ReadCaseLink(string? t)
        {
            var p = _tokens.ReadCaseLink(t);
            if (p == null || p.CaseKind != CaseKind) return (null, null, "Länken gäller inte längre. Den kan ha gått ut (den gäller i 60 dagar).");
            var a = _apps.Get(p.CaseId);
            if (a == null || a.RegionId != p.RegionId) return (null, null, "Ansökan finns inte längre.");
            if (Checksum(a) != p.Checksum)
                return (null, null, "Ansökan har ändrats sedan länken skickades, så länken gäller inte längre. En ny länk skickas när klubben skickar in ändringen.");
            return (a, p, null);
        }

        private async Task<(CompetitionApplication? App, Umbraco.Cms.Core.Models.IMember? Me, IActionResult? Deny)> ClubActionAsync(int id)
        {
            var a = _apps.Get(id);
            if (a == null) return (null, null, Json(new { success = false, message = "Ansökan hittades inte." }));
            var me = await CurrentMemberAsync();
            if (me == null) return (null, null, Json(new { success = false, message = "Logga in först." }));
            if (!await CanClubAsync(a.ClubId, a.RegionId)) return (null, null, Json(new { success = false, message = "Åtkomst nekad" }));
            return (a, me, null);
        }

        private async Task<(CompetitionApplication? App, KretsDecider? Who, IActionResult? Deny)> KretsActionAsync(int id, bool allowHosForbundet = false)
        {
            var a = _apps.Get(id);
            if (a == null) return (null, null, Json(new { success = false, message = "Ansökan hittades inte." }));
            var auth = await KretsAuthorityAsync(a.RegionId);
            if (!auth.Allowed) return (null, null, Json(new { success = false, message = "Åtkomst nekad" }));
            var me = await CurrentMemberAsync();
            return (a, new KretsDecider(me?.Id ?? 0, me == null ? "" : DisplayName(me), auth.Role, KretsChannel.Inloggad), null);
        }

        /// <summary>Klubbens sida: klubbens admin — eller kretsadmin för kretsens egna ansökningar.</summary>
        private async Task<bool> CanClubAsync(int clubId, int regionId)
        {
            if (clubId > 0) return await _auth.IsClubAdminForClub(clubId);
            var region = _calendar.Region(regionId);
            return region != null && await _auth.IsRegionalAdminForRegion(region.Code);
        }

        /// <summary>
        /// Kretsens sida: tävlingsansvarig, kretsadmin eller sajtadmin — och vilken roll som stämplas.
        /// </summary>
        private async Task<(bool Allowed, string Role)> KretsAuthorityAsync(int regionId)
        {
            var region = _calendar.Region(regionId);
            if (region == null) return (false, "");
            var me = await CurrentMemberAsync();
            if (me == null) return (false, "");
            if (_uppdrag.HasUppdrag(regionId, me.Id, BoardRoleDefinitions.RoleTavlingsansvarig))
                return (true, BoardRoleDefinitions.GetLabel(BoardRoleDefinitions.RoleTavlingsansvarig));
            if (await _auth.IsCurrentUserAdminAsync()) return (true, "Sajtadministratör (support)");
            if (await _auth.IsRegionalAdminForRegion(region.Code)) return (true, "Kretsadministratör");
            return (false, "");
        }

        /// <summary>
        /// Får besökaren se planeringskalendern? Kretsens tävlingsansvarige, kretsadmin, sajtadmin —
        /// eller administratör för en klubb i kretsen (de ansöker därifrån).
        /// </summary>
        private async Task<bool> CanPlanAsync(int regionId)
        {
            if ((await KretsAuthorityAsync(regionId)).Allowed) return true;
            var me = await CurrentMemberAsync();
            if (me == null) return false;
            foreach (var cid in _calendar.ClubsInRegion(regionId).Keys)
                if (await _auth.IsClubAdminForClub(cid)) return true;
            return false;
        }

        /// <summary>Direkt klubbadmin (gruppen), utan att kretsadmin räknas — för vilka klubbar kalendern erbjuder.</summary>
        private Task<bool> ClubAdminDirectAsync(int memberId, int clubId)
        {
            try { return Task.FromResult(_memberService.GetAllRoles(memberId).Contains($"ClubAdmin_{clubId}") || _memberService.GetAllRoles(memberId).Contains("Administrators")); }
            catch { return Task.FromResult(false); }
        }

        private async Task<bool> ViewerIsAdminAsync()
        {
            var me = await CurrentMemberAsync();
            if (me == null) return false;
            try
            {
                return _memberService.GetAllRoles(me.Id).Any(r => r == "Administrators" || r.StartsWith("ClubAdmin_") || r.StartsWith("RegionalAdmin_"));
            }
            catch { return false; }
        }

        private string RegionName(int regionId) => _calendar.Region(regionId)?.Name ?? "";

        private string? KretsContact(int regionId)
        {
            var n = UmbracoContext.Content?.GetById(regionId);
            return n?.Value<string>("contactEmail");
        }

        private static string MailMessage(int n, string what) =>
            n > 0 ? $"{what}, och klubben har fått besked." : $"{what}. Mejlet till klubben kunde inte skickas — meddela klubben på annat sätt.";

        private static string EventLabel(string k) => k switch
        {
            CompetitionApplicationEventKind.Created => "Skapad",
            CompetitionApplicationEventKind.Edited => "Ändrad",
            CompetitionApplicationEventKind.Submitted => "Inskickad",
            CompetitionApplicationEventKind.CompletionRequested => "Komplettering begärd",
            CompetitionApplicationEventKind.Replied => "Klubben kompletterade",
            CompetitionApplicationEventKind.Opinion => "Kretsens yttrande",
            CompetitionApplicationEventKind.Approved => "Godkänd",
            CompetitionApplicationEventKind.Rejected => "Avslagen",
            CompetitionApplicationEventKind.SentToForbundet => "Skickad till Förbundet",
            CompetitionApplicationEventKind.ForbundetDecision => "Förbundets beslut",
            CompetitionApplicationEventKind.Withdrawn => "Återkallad",
            CompetitionApplicationEventKind.Linked => "Tävlingen skapad",
            _ => k
        };

        private List<T> SafeList<T>(Func<List<T>> f)
        {
            try { return f(); }
            catch (Exception ex) { _logger.LogWarning(ex, "Tävlingsansökan: läsning misslyckades."); return new(); }
        }

        private static DateTime? ParseDate(string? s) =>
            DateTime.TryParseExact((s ?? "").Trim(), "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var d) ? d : null;

        private static string? Clip(string? s, int max)
        {
            var t = (s ?? "").Trim();
            if (t.Length == 0) return null;
            return t.Length > max ? t[..max] : t;
        }

        private async Task<Umbraco.Cms.Core.Models.IMember?> CurrentMemberAsync()
        {
            var current = await _memberManager.GetCurrentMemberAsync();
            return current?.Email == null ? null : _memberService.GetByEmail(current.Email);
        }

        private static string DisplayName(Umbraco.Cms.Core.Models.IMember m)
        {
            var n = $"{m.GetValue<string>("firstName")} {m.GetValue<string>("lastName")}".Trim();
            return n.Length > 0 ? n : (m.Name ?? "");
        }
    }
}
